services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/app
      - ruby_gems:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  db:
    image: postgres:18-alpine
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
        POSTGRES_DB: focus_mate_development
        POSTGRES_USER: user
        POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d focus_mate_development"]
      interval: 2s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  ruby_gems:
